spring:
  #mvc:
    #static-path-pattern: /static/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  output:
    ansi:
      enabled: always
  profiles:
    default: development
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
logging:
  level:
    org:
      hibernate:
        SQL: debug